environment:
  global:
    CMD_IN_ENV: "cmd /E:ON /V:ON /C obvci_appveyor_python_build_env.cmd"

  ffmpeg_download: https://ffmpeg.zeranoe.com/builds/
  ffmpeg_version: latest

  matrix:
    - PYTHON: "C:\\Python27"
      ffmpeg_platform: win32
    - PYTHON: "C:\\Python27-x64"
      ffmpeg_platform: win64
    - PYTHON: "C:\\Python34"
      ffmpeg_platform: win32
    - PYTHON: "C:\\Python34-x64"
      ffmpeg_platform: win64
    - PYTHON: "C:\\Python35"
      ffmpeg_platform: win32
    - PYTHON: "C:\\Python35-x64"
      ffmpeg_platform: win64
    - PYTHON: "C:\\Python35"
      ffmpeg_platform: win32
    - PYTHON: "C:\\Python35-x64"
      ffmpeg_platform: win64
    - PYTHON: "C:\\Python36"
      ffmpeg_platform: win32
    - PYTHON: "C:\\Python36-x64"
      ffmpeg_platform: win64
    - PYTHON: "C:\\Python37"
      ffmpeg_platform: win32
    - PYTHON: "C:\\Python37-x64"
      ffmpeg_platform: win64
 
install:
  - ps: Start-FileDownload $env:ffmpeg_download$env:ffmpeg_platform/static/ffmpeg-$env:ffmpeg_version-$env:ffmpeg_platform-static.zip
  - 7z x ffmpeg-%ffmpeg_version%-%ffmpeg_platform%-static.zip
  - PATH=%PATH%;%cd%\ffmpeg-%ffmpeg_version%-%ffmpeg_platform%-static\bin
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - "python -m pip install --disable-pip-version-check --user --upgrade pip"
  - "pip install -U setuptools pytest"
  - "pip install coverage pytest-cov codecov"

build_script:
  - "python setup.py install"

test_script:
  - "python setup.py test"


